# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eating' do
  pod 'KakaoSDK'

  target 'EatingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EatingUITests' do
    # Pods for testing
  end

end
